version: '3.7'

services:
  nautilus-simple-ms-1:
    image: nautilus-simple-microservice:1.0.0
    container_name: nautilus-simple-ms-1
    ports:
      - 9090:8080
    env_file:
      - docker.env
    environment:
      - CACHE_INSTANCENAME=nautilus-simple-ms-1
      - CACHE_USER_INITONSTARTUP=true

  nautilus-simple-ms-2:
    image: nautilus-simple-microservice:1.0.0
    container_name: nautilus-simple-ms-2
    ports:
      - 9091:8080
    env_file:
      - docker.env
    environment:
      - CACHE_INSTANCENAME=nautilus-simple-ms-2

  nautilus-simple-ms-3:
    image: nautilus-simple-microservice:1.0.0
    container_name: nautilus-simple-ms-3
    ports:
      - 9092:8080
    env_file:
      - docker.env
    environment:
      - CACHE_INSTANCENAME=nautilus-simple-ms-3